settings:
  legacy:
    force: false
    interval: 1s
schema:
- name: monkeymock
  path: .
  commands:
    test:
      status: true
      method: go test -gcflags=-l ./...
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
    scripts:
      - type: after
        command: go test -v -gcflags=-l ./...
        global: false
        output: true
